package ben_mkiv.rendertoolkit.network;

public enum EventType{
    INTERACT_WORLD_RIGHT, INTERACT_WORLD_LEFT, INTERACT_WORLD_BLOCK_RIGHT, INTERACT_WORLD_BLOCK_LEFT,
    INTERACT_OVERLAY,
    GLASSES_SCREEN_SIZE
}

